on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get -qy install libvips-dev
      - uses: actions/checkout@v2
      - uses: crystal-lang/install-crystal@v1
      - run: shards install
      - run: crystal spec
